// Mock patient data
export const mockPatient = {
    id: 1,
    name: "Maria Silva Santos",
    birthDate: "1985-03-15",
    gender: "Feminino",
    cpf: "123.456.789-00",
    rg: "12.345.678-9",
    phone: "(11) 98765-4321",
    email: "maria.silva@email.com",
    address: "Rua das Flores, 123",
    city: "São Paulo",
    state: "SP",
    zipCode: "01234-567",
    bloodType: "O+",
    allergies: "Penicilina, Dipirona",
    chronicDiseases: "Hipertensão",
    emergencyContact: "João Silva - (11) 91234-5678",
    healthInsurance: "Unimed",
    insuranceNumber: "123456789",
    photo: "/professional-woman-portrait.jpg",
  }
  
  // Mock consultations data
  export const mockConsultations = [
    {
      id: 1,
      date: "2024-01-15",
      time: "14:30",
      doctor: "Dr. Carlos Mendes",
      specialty: "Cardiologia",
      complaint: "Dor no peito e falta de ar",
      diagnosis: "Hipertensão arterial controlada",
      treatment: "Ajuste na medicação anti-hipertensiva",
      prescription: "Losartana 50mg - 1x ao dia\nAAS 100mg - 1x ao dia",
      observations: "Paciente apresentou melhora significativa. Retornar em 3 meses.",
      followUp: "2024-04-15",
    },
    {
      id: 2,
      date: "2023-11-20",
      time: "10:00",
      doctor: "Dra. Ana Paula Costa",
      specialty: "Clínica Geral",
      complaint: "Febre e tosse persistente",
      diagnosis: "Infecção respiratória viral",
      treatment: "Repouso e hidratação",
      prescription: "Paracetamol 750mg - 8/8h se febre\nXarope expectorante - 3x ao dia",
      observations: "Sintomas devem melhorar em 5-7 dias. Retornar se piorar.",
      followUp: null,
    },
    {
      id: 3,
      date: "2023-08-10",
      time: "16:00",
      doctor: "Dr. Roberto Lima",
      specialty: "Ortopedia",
      complaint: "Dor no joelho direito",
      diagnosis: "Tendinite patelar",
      treatment: "Fisioterapia e anti-inflamatórios",
      prescription: "Ibuprofeno 600mg - 8/8h por 7 dias\nFisioterapia - 3x por semana",
      observations: "Evitar atividades de impacto. Usar gelo local 3x ao dia.",
      followUp: "2023-09-10",
    },
  ]
  
  // Mock triage data
  export const mockTriages = [
    {
      id: 1,
      date: "2024-01-15",
      time: "14:15",
      nurse: "Enf. Juliana Oliveira",
      bloodPressure: "130/85",
      heartRate: 78,
      temperature: 36.5,
      respiratoryRate: 16,
      oxygenSaturation: 98,
      weight: 68.5,
      height: 165,
      painLevel: 3,
      classification: "Amarelo - Urgência",
      observations: "Paciente calma, orientada. Refere dor torácica leve.",
    },
    {
      id: 2,
      date: "2023-11-20",
      time: "09:45",
      nurse: "Enf. Pedro Santos",
      bloodPressure: "120/80",
      heartRate: 88,
      temperature: 38.2,
      respiratoryRate: 20,
      oxygenSaturation: 96,
      weight: 67.8,
      height: 165,
      painLevel: 2,
      classification: "Verde - Pouco Urgente",
      observations: "Paciente com febre. Tosse produtiva.",
    },
  ]
  
  // Mock exams data
  export const mockExams = [
    {
      id: 1,
      date: "2024-01-10",
      type: "Hemograma Completo",
      requestedBy: "Dr. Carlos Mendes",
      laboratory: "Laboratório São Lucas",
      status: "Concluído",
      results: "Hemoglobina: 13.5 g/dL (Normal)\nLeucócitos: 7.200/mm³ (Normal)\nPlaquetas: 250.000/mm³ (Normal)",
      observations: "Todos os valores dentro da normalidade.",
    },
    {
      id: 2,
      date: "2024-01-10",
      type: "Eletrocardiograma (ECG)",
      requestedBy: "Dr. Carlos Mendes",
      laboratory: "Clínica CardioVida",
      status: "Concluído",
      results: "Ritmo sinusal regular\nFrequência: 72 bpm\nEixo normal\nSem alterações isquêmicas",
      observations: "ECG dentro dos padrões de normalidade.",
    },
    {
      id: 3,
      date: "2023-11-15",
      type: "Raio-X de Tórax",
      requestedBy: "Dra. Ana Paula Costa",
      laboratory: "Centro de Imagem Diagnóstica",
      status: "Concluído",
      results: "Campos pulmonares livres\nÍndice cardiotorácico normal\nSeios costofrênicos livres",
      observations: "Sem alterações radiológicas significativas.",
    },
    {
      id: 4,
      date: "2023-08-05",
      type: "Ressonância Magnética - Joelho Direito",
      requestedBy: "Dr. Roberto Lima",
      laboratory: "Centro de Diagnóstico por Imagem",
      status: "Concluído",
      results: "Edema no tendão patelar\nSem lesões ligamentares\nCartilagem preservada",
      observations: "Achados compatíveis com tendinite patelar.",
    },
    {
      id: 5,
      date: "2024-02-01",
      type: "Ultrassom Abdominal",
      requestedBy: "Dra. Ana Paula Costa",
      laboratory: "Clínica de Imagem Avançada",
      status: "Aguardando",
      results: null,
      observations: "Exame agendado para 01/02/2024.",
    },
  ]
  
  // Mock vaccines data
  export const mockVaccines = [
    {
      id: 1,
      date: "2023-04-10",
      vaccine: "Influenza (Gripe)",
      dose: "Dose Anual",
      batch: "FLU2023A",
      manufacturer: "Instituto Butantan",
      appliedBy: "Enf. Carla Rodrigues",
      location: "UBS Vila Mariana",
      nextDose: "2024-04-10",
      observations: "Sem reações adversas.",
    },
    {
      id: 2,
      date: "2022-06-15",
      vaccine: "COVID-19 (Pfizer)",
      dose: "2ª Dose de Reforço",
      batch: "COVID2022B",
      manufacturer: "Pfizer",
      appliedBy: "Enf. Marcos Silva",
      location: "Centro de Vacinação - Shopping",
      nextDose: null,
      observations: "Paciente apresentou leve dor no local da aplicação.",
    },
    {
      id: 3,
      date: "2020-03-20",
      vaccine: "Tétano e Difteria (dT)",
      dose: "Reforço",
      batch: "DT2020C",
      manufacturer: "Fundação Oswaldo Cruz",
      appliedBy: "Enf. Paula Mendes",
      location: "UBS Vila Mariana",
      nextDose: "2030-03-20",
      observations: "Sem intercorrências.",
    },
    {
      id: 4,
      date: "2019-11-05",
      vaccine: "Hepatite B",
      dose: "3ª Dose",
      batch: "HEPB2019D",
      manufacturer: "Instituto Butantan",
      appliedBy: "Enf. Roberto Costa",
      location: "Clínica Particular",
      nextDose: null,
      observations: "Esquema vacinal completo.",
    },
  ]
  